services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: playground_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: yes
    ports:
      - '3307:3306'

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=your_secure_password"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
  app:
    image: spring-boot-playground:latest
    container_name: rest_playground
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/playground_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

